# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  # - MediumFollowersCountPlugin:
      # username: GuillaumeKuc
  # Automatically fetch Github repo star count
  # - GithubRepoStarsCountPlugin:
      #- Guillaume Kuc/ZMarkupParser
      #- Guillaume Kuc/ZReviewTender
      #- Guillaume Kuc/ZMediumToMarkdown
      #- Guillaume Kuc/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Guillaume Kuc's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "@guillaumekuc"

# Tagline section text
tagline: >-
    Technical Artist from France. 2D/3D Digital Arts, Music Production, Scripting & Tools Development.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-folder-open"
      text: "Portfolio"
      url: "https://guillaumekuc.art/"
      alt: "Guillaume Kuc's Portfolio Website"
      title: "Guillaume Kuc's Portfolio Website"
      target: "_blank"
  - link:
      icon: "fa-solid fa-pen"
      text: "Blog" # <span class='link-button-text'>({{vars.MediumFollowersCountPlugin}} Followers)</span>
      url: "https://guillaumekuc.github.io/blog/"
      alt: "Guillaume Kuc's Blog"
      title: "Guillaume Kuc's Blog"
      target: "_blank"
  - link:
      icon: "fa-solid fa-file-lines"
      text: "Resume" # <span class='link-button-text'>({{vars.MediumFollowersCountPlugin}} Followers)</span>
      url: "https://guillaumekuc.github.io/resume/"
      alt: "Guillaume Kuc's Resume"
      title: "Guillaume Kuc's Resume"
      target: "_blank"
  - link:
      icon: "fa-solid fa-coffee"
      text: "Coffee Tip!"
      url: "https://buymeacoffee.com/guillaumekuc"
      alt: "Guillaume Kuc's Buy Me a Coffee"
      title: "Guillaume Kuc's Buy Me a Coffee"
      target: "_blank"
      class: "highlight"




# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/guillaumekuc"
      title: "GitHub"
      alt: "Guillaume Kuc's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-artstation"
      url: "https://artstation.com/guillaumekuc"
      title: "ArtStation"
      alt: "Guillaume Kuc's ArtStation"
      target: "_blank"
  - social:
      icon: "fa-brands fa-soundcloud"
      url: "https://soundcloud.com/guillaume-kuc-945925946"
      title: "SoundCloud"
      alt: "Guillaume Kuc's SoundCloud"
      target: "_blank"
  - social:
      icon: "fa-brands fa-bluesky"
      url: "https://@guillaumekuc.bsky.social"
      title: "Bluesky"
      alt: "Guillaume Kuc's Bluesky"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/guillaumekuc/"
      title: "LinkedIn"
      alt: "Guillaume Kuc's LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:guillaume@guillaumekuc.com"
      title: "Email: guillaume@guillaumekuc.com"
      alt: "guillaume@guillaumekuc.com"
      target: "_blank"

# Footer text
footer: >
    Hi there! Follow me on Medium or GitHub, or stay connected on Bluesky or LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2024  <a href="https://guillaumekuc.art" target="_blank">Guillaume Kuc</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
